# Generated by Django 5.0.7 on 2024-08-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_owner'),
        ('user', '0008_rename_social_youtube_profile_social_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='user.profile'),
        ),
    ]
