# Generated by Django 5.0.7 on 2024-08-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_options_review_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
    ]
