# Generated by Django 5.0.7 on 2024-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Up')], default=('up', 'Up Vote'), max_length=200),
        ),
    ]
