# Generated by Django 5.0.7 on 2024-08-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_review_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratios', '-vote_total', 'title']},
        ),
    ]
