# Generated by Django 5.0.7 on 2024-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_options'),
        ('user', '0008_rename_social_youtube_profile_social_twitter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
