# Generated by Django 5.0.7 on 2024-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_project_options_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_img',
            field=models.ImageField(blank=True, default='/images/default.img', null=True, upload_to=''),
        ),
    ]
