# Generated by Django 5.0.7 on 2024-08-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='descrptiion',
            new_name='descrption',
        ),
    ]
