# Generated by Django 5.0.7 on 2024-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_descrptiion_skill_descrption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_twitter',
            new_name='social_stackoverflow',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
