# Generated by Django 5.0.7 on 2024-08-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_social_twitter_profile_social_stackoverflow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_youtube',
            new_name='social_twitter',
        ),
    ]
