# Generated by Django 5.0.7 on 2024-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(choices=[('Readed', 'yes'), ('not readed', 'no')], default=False),
        ),
    ]
